### ISSUE TITLE
Rename of package on npm

### ISSUE THREAD

**Issue by rishabh3112** [sendilkumarn/webpack-scaffold-pwa#20]
Webpack CLI allows only those packages to scaffold that starts with `webpack-scaffold`.
The [package](https://www.npmjs.com/package/webpack-addons-pwa) at npm needed to be changed to `webpack-scaffold-pwa`

**Comment by sendilkumarn** [comment]
Thanks @rishabh3112 I will release it within this weekend

**Comment by sendilkumarn** [comment]
Between if you are interested You can start working on #11 or #13

**Comment by sendilkumarn** [comment]
Yay! published 0.0.1 🎉
