### ISSUE TITLE
Bug: output.filename is not resolved

### ISSUE THREAD

**Issue by rishabh3112** [sendilkumarn/webpack-scaffold-pwa#25]
In scaffolded configuration output.filename is not resolved

**Comment by sendilkumarn** [comment]
Is this valid anymore?

**Comment by rishabh3112** [comment]
Well, Yes.
It would be awesome if we ask the user about this or giving a generic name like `bundle.js` would also work.
Your thoughts @sendilkumarn?.

**Comment by sendilkumarn** [comment]
Well yeah, that makes sense we can give a default name now, asking user may be in future ?
