### ISSUE TITLE
Disscussion: Create manifest using WebappWebpackPlugin

### ISSUE THREAD

**Issue by rishabh3112** [sendilkumarn/webpack-scaffold-pwa#26]
To solve #11 using #22 and #24 I used WebappWebpackPlugin. It has inbuilt manifest generation support.
So, I think we should switch to WebappWebpackPlugin for this.

Pinging @dhruvdutt @sendilkumarn for disscussion

**Comment by sendilkumarn** [comment]
That would be awesome, at any point removing a dependency is FTW. 

Lets do it 👍 🎉

**Comment by rishabh3112** [comment]
There are some pros and cons to this approach:
## Pros
1. Codebase becomes smaller.
2. Easily manageable.
3. Remove dependencies like `copy-webpack-plugin`.
## Cons
1. WebappWebpackPlugin doesn't let us update `start_url` #29 
2. WebappWebpack doesn't support already made `manifest.json` thus less flexibility for the user.
3. Must have a favicon (have added a fallback favicon though in #42 ).

If objectives don't clash with cons then I think we should work further towards this change,
You thoughts @sendilkumarn?

**Comment by sendilkumarn** [comment]
@rishabh3112 Thanks for writing this down.


> WebappWebpackPlugin doesn't let us update start_url 

Cant we change this using the properties available in webappWPPlugin

> WebappWebpack doesn't support already made manifest.json thus less flexibility for the user.

I think we can read the manifest and create this configuration, in future.


>Must have a favicon (have added a fallback favicon though in #42 ).

I am okay to add a default favicon here.

**Comment by rishabh3112** [comment]
> Cant we change this using the properties available in webappWPPlugin

No, @sendilkumarn as it doesn't have property under favicon object for this, see all customiseable properties below:
```js
plugins: [
  new WebappWebpackPlugin({
    // Your source logo (required)
    logo: '/path/to/logo.png',
    // Enable caching and optionally specify the path to store cached data
    // Note: disabling caching may increase build times considerably
    cache: true,
    // Prefix path for generated assets
    prefix: 'assets/',
    // Inject html links/metadata (requires html-webpack-plugin)
    // false: disables injection
    // true: enables injection if that is not disabled in html-webpack-plugin
    // 'force': enables injection even if that is disabled in html-webpack-plugin
    inject: true,
    favicons: {
      appName: 'my-app',
      appDescription: 'My awesome App',
      developerName: 'Me',
      developerURL: null, // prevent retrieving from the nearest package.json
      background: '#ddd',
      theme_color: '#333',
      icons: {
        coast: false,
        yandex: false
      }
    }
  })
]
```

**Comment by rishabh3112** [comment]
How should I proceed on this now @sendilkumarn?

**Comment by sendilkumarn** [comment]
Did you check [this](https://github.com/brunocodutra/webapp-webpack-plugin/issues/28#issuecomment-373032807) out

**Comment by rishabh3112** [comment]
Well, I just looked at the formal documentation earlier.
Will update in next commit at #42.

**Comment by rishabh3112** [comment]
And can we chat on gitter from now @sendilkumarn?

**Comment by sendilkumarn** [comment]
[slack](https://join.slack.com/t/webpack-scaffold-pwa/shared_invite/enQtNDA4NTc5MTIzMjgzLTM5NmRjYjc4ZmFjNmY0YjBiZDhiZjIxNDcwODhiOGE5ZGIyNWU4NGU1MjVlZWNmZjMwYmMwYmJjZGJjYzcwOWY)
