### ISSUE TITLE
Package: the dependencies should go to devdeps

### ISSUE THREAD

**Issue by sendilkumarn** [sendilkumarn/webpack-scaffold-pwa#31]

**Comment by rishabh3112** [comment]
Dependencies are indeed going to `devDependencies`. Here is a look to `devDependencies` of sample app scaffolded through this plugin.
```json
"devDependencies": {
    "@webpack-cli/init": "^0.1.0",
    "copy-webpack-plugin": "^4.5.2",
    "html-webpack-plugin": "^3.2.0",
    "webapp-webpack-plugin": "^2.3.0",
    "webpack": "^4.16.2",
    "webpack-cli": "^3.1.0",
    "workbox-webpack-plugin": "^3.4.1"
  }
```
@sendilkumarn, Was this diffrent in your case or you refer to some other problem here??

**Comment by sendilkumarn** [comment]
Interesting for me it is going into `dependencies` interesting

**Comment by rishabh3112** [comment]
![20180730_104347](https://user-images.githubusercontent.com/15812317/43378643-d45b277c-93e5-11e8-8d79-c04dcf1dabb2.png)
This snippet in `generator.js` is there for this.
But what happened in your case was interesting indeed 😅

**Comment by rishabh3112** [comment]
Any updates on this @sendilkumarn ??

**Comment by sendilkumarn** [comment]
The issue is that we just use the flag `--save-dev` which will not work when using `yarn`
