### ISSUE TITLE
Feature: Setup CSS preprocessors and babel(any js complier) as per user

### ISSUE THREAD

**Issue by rishabh3112** [sendilkumarn/webpack-scaffold-pwa#44]

**Comment by AjayPoshak** [comment]
I want to work on it.

**Comment by sendilkumarn** [comment]
@AjayPoshak Can you please wait?

@rishabh3112 what is the intention here? Why do we need it? What is advantage of PWA to have them?

**Comment by sendilkumarn** [comment]
I would say if it is not about PWA, we can hold it for now. 

Closing this for now. Feel free to open it again, if you would like to discuss this further
